### ISSUE TITLE
ModuleNotFoundError: No module named 'unimat'

### ISSUE THREAD

**Issue by shimurenhlq** [dptech-corp/Uni-MOF#3]
I encountered the following problem while trying to replicate the experiment. How can I solve it?

Command：bash unimof_pretrain.sh

Problems:
Traceback (most recent call last):
  File "/home/lizc/.conda/envs/Uni-MOF/bin/unicore-train", line 8, in <module>
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
    sys.exit(cli_main())
  File "/home/lizc/.conda/envs/Uni-MOF/lib/python3.9/site-packages/unicore_cli/train.py", line 411, in cli_main
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/data/share/gourd/Uni-MOF/unimof/__init__.py", line 2, in <module>
    parser = options.get_training_parser()
  File "/home/lizc/.conda/envs/Uni-MOF/lib/python3.9/site-packages/unicore/options.py", line 25, in get_training_parser
    parser = get_parser("Trainer", default_task)
      File "/home/lizc/.conda/envs/Uni-MOF/lib/python3.9/site-packages/unicore/options.py", line 165, in get_parser
import unimat.tasks
ModuleNotFoundError: No module named 'unimat'

**Comment by ashuai27** [comment]
你好，我在读源码也遇到了相同的问题，没有找到unimat的位置，请问你解决了吗。想加您的联系方式，共同探讨下

**Comment by KoitAgosti** [comment]
将unimof下的__init__.py改写为
import importlib
import unicore.tasks
import unicore.data
import unicore.models
import unicore.losses，这样会有新的bug：usage: unicore-train [-h] [--no-progress-bar] [--log-interval N]
                     [--log-format {json,none,simple,tqdm}]
                     [--tensorboard-logdir DIR] [--wandb-project DIR]
                     [--wandb-name DIR] [--seed N] [--cpu] [--fp16] [--bf16]
                     [--bf16-sr] [--allreduce-fp32-grad]
                     [--fp16-no-flatten-grads]
                     [--fp16-init-scale FP16_INIT_SCALE]
                     [--fp16-scale-window FP16_SCALE_WINDOW]
                     [--fp16-scale-tolerance FP16_SCALE_TOLERANCE]
                     [--min-loss-scale D]
                     [--threshold-loss-scale THRESHOLD_LOSS_SCALE]
                     [--user-dir USER_DIR]
                     [--empty-cache-freq EMPTY_CACHE_FREQ]
                     [--all-gather-list-size ALL_GATHER_LIST_SIZE]
                     [--suppress-crashes] [--profile] [--ema-decay EMA_DECAY]
                     [--validate-with-ema] [--loss {cross_entropy,masked_lm}]
                     [--optimizer {adadelta,adagrad,adam,sgd}]
                     [--lr-scheduler {cosine,exponential_decay,fixed,inverse_sqrt,pass_through,polynomial_decay,reduce_lr_on_plateau,tri_stage,triangular}]
                     [--task TASK] [--num-workers N]
                     [--skip-invalid-size-inputs-valid-test] [--batch-size N]
                     [--required-batch-size-multiple N]
                     [--data-buffer-size DATA_BUFFER_SIZE]
                     [--train-subset SPLIT] [--valid-subset SPLIT]
                     [--validate-interval N] [--validate-interval-updates N]
                     [--validate-after-updates N] [--fixed-validation-seed N]
                     [--disable-validation] [--batch-size-valid N]
                     [--max-valid-steps N] [--curriculum N]
                     [--distributed-world-size N]
                     [--distributed-rank DISTRIBUTED_RANK]
                     [--distributed-backend DISTRIBUTED_BACKEND]
                     [--distributed-init-method DISTRIBUTED_INIT_METHOD]
                     [--distributed-port DISTRIBUTED_PORT]
                     [--device-id DEVICE_ID] [--distributed-no-spawn]
                     [--ddp-backend {c10d,apex,no_c10d}] [--bucket-cap-mb MB]
                     [--fix-batches-to-gpus] [--find-unused-parameters]
                     [--fast-stat-sync] [--broadcast-buffers]
                     [--nprocs-per-node NPROCS_PER_NODE] --arch ARCH
                     [--max-epoch N] [--max-update N]
                     [--stop-time-hours STOP_TIME_HOURS] [--clip-norm NORM]
                     [--per-sample-clip-norm PNORM]
                     [--update-freq N1,N2,...,N_K] [--lr LR_1,LR_2,...,LR_N]
                     [--stop-min-lr LR] [--save-dir DIR] [--tmp-save-dir DIR]
                     [--restore-file RESTORE_FILE]
                     [--finetune-from-model FINETUNE_FROM_MODEL]
                     [--load-from-ema] [--reset-dataloader]
                     [--reset-lr-scheduler] [--reset-meters]
                     [--reset-optimizer] [--optimizer-overrides DICT]
                     [--save-interval N] [--save-interval-updates N]
                     [--keep-interval-updates N] [--keep-last-epochs N]
                     [--keep-best-checkpoints N] [--no-save]
                     [--no-epoch-checkpoints] [--no-last-checkpoints]
                     [--no-save-optimizer-state]
                     [--best-checkpoint-metric BEST_CHECKPOINT_METRIC]
                     [--maximize-best-checkpoint-metric] [--patience N]
                     [--checkpoint-suffix CHECKPOINT_SUFFIX]
unicore-train: error: argument --task: invalid choice: 'unimat' (choose from )
fused_multi_tensor is not installed corrected
fused_rounding is not installed corrected
fused_layer_norm is not installed corrected
fused_rms_norm is not installed corrected
fused_softmax is not installed corrected

**Comment by ashuai27** [comment]
这个问题解决了，应该是作者在早期版本一直使用的unimat文件夹作为名字，把所有的导入unimat的模块都改成导入unimof就解决了
